import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "te" | "kn" | "hi" | "ta";

export interface LanguageOption {
  code: Language;
  name: string;
  nativeName: string;
}

export const languages: LanguageOption[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, replacements?: Record<string, string | number>) => string;
  currentLanguage: LanguageOption;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys - comprehensive for entire app
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    "common.welcome": "Welcome",
    "common.enabled": "Enabled",
    "common.disabled": "Disabled",
    "common.minutes": "minutes",
    "common.minute": "minute",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.add": "Add",
    "common.search": "Search",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.confirm": "Confirm",
    "common.back": "Back",
    "common.next": "Next",
    "common.done": "Done",
    "common.close": "Close",
    "common.yes": "Yes",
    "common.no": "No",
    "common.ok": "OK",
    "common.documents": "Documents",
    "common.document": "Document",
    "common.noResults": "No results found",
    "common.tryAgain": "Try again",
    "common.view": "View",
    "common.download": "Download",
    "common.upload": "Upload",
    "common.create": "Create",
    "common.update": "Update",
    "common.remove": "Remove",
    
    // Navigation
    "nav.home": "Home",
    "nav.vault": "Vault",
    "nav.settings": "Settings",
    
    // Dashboard
    "dashboard.welcome": "Welcome,",
    "dashboard.securityScore": "Security Score",
    "dashboard.docs": "Docs",
    "dashboard.nominees": "Nominees",
    "dashboard.capsules": "Capsules",
    "dashboard.trigger": "Trigger",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.noQuickActions": "No quick actions enabled",
    "dashboard.triggerEnabled": "Trigger is enabled",
    "dashboard.triggerDisabled": "Trigger is disabled",
    
    // Vault
    "vault.title": "My Vault",
    "vault.documents": "Documents",
    "vault.searchPlaceholder": "Search documents, categories, dates...",
    "vault.resultsFound": "{count} results found",
    "vault.noResults": "No results found",
    "vault.noResultsDesc": "Try adjusting your search or browse all categories",
    "vault.clearSearch": "Clear Search",
    "vault.addCategory": "Add Category",
    "vault.categoryName": "Category Name",
    "vault.categoryNamePlaceholder": "Enter category name",
    "vault.createCategory": "Create Category",
    "vault.deleteCategory": "Delete Category",
    "vault.deleteCategoryConfirm": "Are you sure you want to delete this category? All documents inside will be moved to trash.",
    "vault.categoryCreated": "Category created!",
    "vault.categoryDeleted": "Category deleted",
    "vault.cannotDelete": "Cannot delete",
    "vault.defaultCategoryError": "Default categories cannot be deleted",
    "vault.noDocuments": "No documents yet",
    "vault.uploadFirst": "Upload your first document",
    "vault.manageAccess": "Manage Access",
    "vault.whoHasAccess": "Who has access",
    "vault.matches": "matches",
    "vault.match": "match",
    
    // Documents
    "document.upload": "Upload Document",
    "document.view": "View Document",
    "document.download": "Download",
    "document.delete": "Delete Document",
    "document.deleteConfirm": "Are you sure you want to delete this document?",
    "document.uploaded": "Document uploaded",
    "document.deleted": "Document deleted",
    "document.lock": "Lock Document",
    "document.unlock": "Unlock Document",
    "document.password": "Password",
    "document.confirmPassword": "Confirm Password",
    "document.fromDevice": "From Device",
    "document.fromGoogleDrive": "From Google Drive",
    "document.scanDocument": "Scan Document",
    "document.maxSize": "Maximum file size: 20MB",
    
    // Nominees
    "nominee.title": "Nominees",
    "nominee.subtitle": "Manage your trusted contacts",
    "nominee.add": "Add Nominee",
    "nominee.edit": "Edit Nominee",
    "nominee.delete": "Delete Nominee",
    "nominee.deleteConfirm": "Are you sure you want to remove this nominee?",
    "nominee.fullName": "Full Name",
    "nominee.email": "Email",
    "nominee.phone": "Phone",
    "nominee.relation": "Relation",
    "nominee.pending": "Pending",
    "nominee.verified": "Verified",
    "nominee.sendVerification": "Send Verification",
    "nominee.resendVerification": "Resend Verification",
    "nominee.noNominees": "No nominees added",
    "nominee.addFirst": "Add your first nominee to share access",
    
    // Time Capsule
    "timeCapsule.title": "Time Capsule",
    "timeCapsule.subtitle": "Schedule messages for the future",
    "timeCapsule.create": "Create Time Capsule",
    "timeCapsule.edit": "Edit Time Capsule",
    "timeCapsule.delete": "Delete Time Capsule",
    "timeCapsule.deleteConfirm": "Are you sure you want to delete this time capsule?",
    "timeCapsule.messageTitle": "Title",
    "timeCapsule.message": "Message",
    "timeCapsule.recipientEmail": "Recipient Email",
    "timeCapsule.releaseDate": "Release Date",
    "timeCapsule.attachment": "Attachment",
    "timeCapsule.addAttachment": "Add Attachment",
    "timeCapsule.scheduled": "Scheduled",
    "timeCapsule.released": "Released",
    "timeCapsule.noCapsules": "No time capsules",
    "timeCapsule.createFirst": "Create your first time capsule",
    
    // Profile
    "profile.title": "Profile",
    "profile.subtitle": "Manage your profile",
    "profile.edit": "Edit Profile",
    "profile.fullName": "Full Name",
    "profile.email": "Email",
    "profile.phone": "Phone",
    "profile.dateOfBirth": "Date of Birth",
    "profile.changePhoto": "Change Photo",
    "profile.updated": "Profile updated",
    
    // Settings page
    "settings.title": "Settings",
    "settings.subtitle": "Manage your preferences",
    "settings.changePassword": "Change Password",
    "settings.changePassword.subtitle": "Update your password",
    "settings.emailPreferences": "Email Preferences",
    "settings.emailPreferences.subtitle": "Manage email settings",
    "settings.twoFactorAuth": "Two-Factor Auth",
    "settings.twoFactorAuth.subtitle": "Extra security layer",
    "settings.twoFactorAuth.enabled": "Enabled",
    "settings.appLock": "App Lock",
    "settings.appLock.subtitle": "PIN or Biometric",
    "settings.appLock.active": "Active",
    "settings.activeSessions": "Active Sessions",
    "settings.activeSessions.subtitle": "Manage logged-in devices",
    "settings.pushNotifications": "Push Notifications",
    "settings.pushNotifications.subtitle": "Get mobile alerts",
    "settings.pushNotifications.mobileOnly": "Only available on mobile app",
    "settings.autoLockTimeout": "Auto Lock Timeout",
    "settings.backupRestore": "Backup & Restore",
    "settings.backupRestore.subtitle": "Export or restore your vault",
    "settings.helpSupport": "Help & Support",
    "settings.helpSupport.subtitle": "FAQs, guides & contact",
    "settings.language": "Language",
    "settings.language.subtitle": "Change app language",
    "settings.signOut": "Sign Out",
    "settings.deleteAccount": "Delete Account",
    "settings.deleteAccount.title": "Delete Account",
    "settings.deleteAccount.description": "Are you sure you want to delete your account? This action cannot be undone. All your data, documents, and settings will be permanently deleted.",
    "settings.deleteAccount.confirm": "Delete Account",
    "settings.deleting": "Deleting...",
    "settings.appVersion": "App Version 2.0.0",
    
    // Language page
    "language.title": "Language",
    "language.subtitle": "Choose your preferred language",
    "language.current": "Current",
    
    // Auth
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.signOut": "Sign Out",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.forgotPassword": "Forgot Password?",
    "auth.resetPassword": "Reset Password",
    "auth.newPassword": "New Password",
    "auth.currentPassword": "Current Password",
    "auth.createAccount": "Create Account",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.dontHaveAccount": "Don't have an account?",
    "auth.signInWithGoogle": "Sign in with Google",
    "auth.signUpWithGoogle": "Sign up with Google",
    "auth.orContinueWith": "Or continue with",
    "auth.enterOtp": "Enter OTP",
    "auth.otpSent": "OTP sent to your email",
    "auth.verify": "Verify",
    "auth.resendOtp": "Resend OTP",
    
    // Notifications
    "notifications.title": "Notifications",
    "notifications.noNotifications": "No notifications",
    "notifications.markAsRead": "Mark as read",
    "notifications.markAllRead": "Mark all as read",
    "notifications.clearAll": "Clear all",
    
    // Help Center
    "help.title": "Help & Support",
    "help.subtitle": "How can we help you?",
    "help.faq": "Frequently Asked Questions",
    "help.contact": "Contact Support",
    "help.call": "Call",
    "help.email": "Email",
    "help.whatsapp": "WhatsApp",
    "help.sendMessage": "Send Message",
    "help.yourMessage": "Your Message",
    
    // Toasts
    "toast.signedOut": "Signed out",
    "toast.signedOut.description": "See you soon!",
    "toast.accountDeleted": "Account Deleted",
    "toast.accountDeleted.description": "Your account has been permanently deleted",
    "toast.deleteFailed": "Delete Failed",
    "toast.error": "Error",
    "toast.pushEnabled": "Push Notifications Enabled",
    "toast.pushEnabled.description": "You'll receive alerts on this device",
    "toast.pushDisabled": "Push Notifications Disabled",
    "toast.permissionDenied": "Permission Denied",
    "toast.permissionDenied.description": "Please enable notifications in your device settings",
    "toast.languageChanged": "Language Changed",
    "toast.saved": "Saved",
    "toast.updated": "Updated",
    "toast.deleted": "Deleted",
    "toast.copied": "Copied to clipboard",
    "toast.uploadSuccess": "Upload successful",
    "toast.uploadFailed": "Upload failed",
    "toast.downloadStarted": "Download started",
    
    // Backup
    "backup.title": "Backup & Restore",
    "backup.subtitle": "Manage your data backups",
    "backup.create": "Create Backup",
    "backup.restore": "Restore Backup",
    "backup.history": "Backup History",
    "backup.frequency": "Backup Frequency",
    "backup.lastBackup": "Last Backup",
    "backup.noBackups": "No backups yet",
    
    // Security
    "security.twoFactor": "Two-Factor Authentication",
    "security.biometric": "Biometric Login",
    "security.appLock": "App Lock",
    "security.pinLock": "PIN Lock",
    "security.setupPin": "Set up PIN",
    "security.enterPin": "Enter PIN",
    "security.confirmPin": "Confirm PIN",
    "security.wrongPin": "Wrong PIN",
    "security.pinMismatch": "PINs do not match",
    "security.pinSet": "PIN set successfully",
    
    // Inactivity
    "inactivity.title": "Inactivity Trigger",
    "inactivity.subtitle": "Set up emergency access",
    "inactivity.threshold": "Inactivity Threshold",
    "inactivity.days": "days",
    "inactivity.message": "Custom Message",
    "inactivity.enabled": "Trigger Enabled",
    "inactivity.disabled": "Trigger Disabled",
    
    // Access Control
    "access.manageAccess": "Manage Access",
    "access.grantAccess": "Grant Access",
    "access.revokeAccess": "Revoke Access",
    "access.viewOnly": "View Only",
    "access.downloadOnly": "Download Only",
    "access.viewAndDownload": "View and Download",
    "access.selectNominee": "Select Nominee",
    "access.accessLevel": "Access Level",
    "access.noAccess": "No access granted",
  },
  te: {
    // Common
    "common.welcome": "స్వాగతం",
    "common.enabled": "ఆన్ చేయబడింది",
    "common.disabled": "ఆఫ్ చేయబడింది",
    "common.minutes": "నిమిషాలు",
    "common.minute": "నిమిషం",
    "common.save": "సేవ్ చేయండి",
    "common.cancel": "రద్దు చేయండి",
    "common.delete": "తొలగించు",
    "common.edit": "మార్చు",
    "common.add": "జోడించు",
    "common.search": "శోధించు",
    "common.loading": "లోడ్ అవుతోంది...",
    "common.error": "లోపం",
    "common.success": "విజయం",
    "common.confirm": "నిర్ధారించు",
    "common.back": "వెనక్కి",
    "common.next": "తదుపరి",
    "common.done": "పూర్తయింది",
    "common.close": "మూసివేయి",
    "common.yes": "అవును",
    "common.no": "కాదు",
    "common.ok": "సరే",
    "common.documents": "డాక్యుమెంట్లు",
    "common.document": "డాక్యుమెంట్",
    "common.noResults": "ఫలితాలు లేవు",
    "common.tryAgain": "మళ్ళీ ప్రయత్నించండి",
    "common.view": "చూడండి",
    "common.download": "డౌన్లోడ్",
    "common.upload": "అప్లోడ్",
    "common.create": "సృష్టించు",
    "common.update": "అప్డేట్",
    "common.remove": "తొలగించు",
    
    // Navigation
    "nav.home": "హోమ్",
    "nav.vault": "వాల్ట్",
    "nav.settings": "సెట్టింగ్స్",
    
    // Dashboard
    "dashboard.welcome": "స్వాగతం,",
    "dashboard.securityScore": "భద్రతా స్కోర్",
    "dashboard.docs": "డాక్స్",
    "dashboard.nominees": "నామినీలు",
    "dashboard.capsules": "క్యాప్సూల్స్",
    "dashboard.trigger": "ట్రిగ్గర్",
    "dashboard.quickActions": "త్వరిత చర్యలు",
    "dashboard.noQuickActions": "త్వరిత చర్యలు ఆన్ కాలేదు",
    "dashboard.triggerEnabled": "ట్రిగ్గర్ ఆన్ చేయబడింది",
    "dashboard.triggerDisabled": "ట్రిగ్గర్ ఆఫ్ చేయబడింది",
    
    // Vault
    "vault.title": "నా వాల్ట్",
    "vault.documents": "డాక్యుమెంట్లు",
    "vault.searchPlaceholder": "డాక్యుమెంట్లు, కేటగిరీలు శోధించండి...",
    "vault.resultsFound": "{count} ఫలితాలు కనుగొనబడ్డాయి",
    "vault.noResults": "ఫలితాలు లేవు",
    "vault.noResultsDesc": "మీ శోధనను సర్దుబాటు చేయండి లేదా అన్ని కేటగిరీలు చూడండి",
    "vault.clearSearch": "శోధన క్లియర్ చేయండి",
    "vault.addCategory": "కేటగిరీ జోడించు",
    "vault.categoryName": "కేటగిరీ పేరు",
    "vault.categoryNamePlaceholder": "కేటగిరీ పేరు నమోదు చేయండి",
    "vault.createCategory": "కేటగిరీ సృష్టించు",
    "vault.deleteCategory": "కేటగిరీ తొలగించు",
    "vault.deleteCategoryConfirm": "మీరు ఈ కేటగిరీని తొలగించాలనుకుంటున్నారా?",
    "vault.categoryCreated": "కేటగిరీ సృష్టించబడింది!",
    "vault.categoryDeleted": "కేటగిరీ తొలగించబడింది",
    "vault.cannotDelete": "తొలగించలేరు",
    "vault.defaultCategoryError": "డిఫాల్ట్ కేటగిరీలను తొలగించలేరు",
    "vault.noDocuments": "డాక్యుమెంట్లు లేవు",
    "vault.uploadFirst": "మీ మొదటి డాక్యుమెంట్ అప్లోడ్ చేయండి",
    "vault.manageAccess": "యాక్సెస్ నిర్వహించు",
    "vault.whoHasAccess": "ఎవరికి యాక్సెస్ ఉంది",
    "vault.matches": "మ్యాచ్‌లు",
    "vault.match": "మ్యాచ్",
    
    // Documents
    "document.upload": "డాక్యుమెంట్ అప్లోడ్",
    "document.view": "డాక్యుమెంట్ చూడండి",
    "document.download": "డౌన్లోడ్",
    "document.delete": "డాక్యుమెంట్ తొలగించు",
    "document.deleteConfirm": "మీరు ఈ డాక్యుమెంట్‌ను తొలగించాలనుకుంటున్నారా?",
    "document.uploaded": "డాక్యుమెంట్ అప్లోడ్ అయింది",
    "document.deleted": "డాక్యుమెంట్ తొలగించబడింది",
    "document.lock": "డాక్యుమెంట్ లాక్ చేయండి",
    "document.unlock": "డాక్యుమెంట్ అన్‌లాక్ చేయండి",
    "document.password": "పాస్‌వర్డ్",
    "document.confirmPassword": "పాస్‌వర్డ్ నిర్ధారించండి",
    "document.fromDevice": "పరికరం నుండి",
    "document.fromGoogleDrive": "Google Drive నుండి",
    "document.scanDocument": "డాక్యుమెంట్ స్కాన్",
    "document.maxSize": "గరిష్ట ఫైల్ సైజు: 20MB",
    
    // Nominees
    "nominee.title": "నామినీలు",
    "nominee.subtitle": "మీ విశ్వసనీయ పరిచయాలను నిర్వహించండి",
    "nominee.add": "నామినీ జోడించు",
    "nominee.edit": "నామినీ మార్చు",
    "nominee.delete": "నామినీ తొలగించు",
    "nominee.deleteConfirm": "మీరు ఈ నామినీని తొలగించాలనుకుంటున్నారా?",
    "nominee.fullName": "పూర్తి పేరు",
    "nominee.email": "ఇమెయిల్",
    "nominee.phone": "ఫోన్",
    "nominee.relation": "సంబంధం",
    "nominee.pending": "పెండింగ్",
    "nominee.verified": "ధృవీకరించబడింది",
    "nominee.sendVerification": "ధృవీకరణ పంపండి",
    "nominee.resendVerification": "ధృవీకరణ మళ్ళీ పంపండి",
    "nominee.noNominees": "నామినీలు జోడించలేదు",
    "nominee.addFirst": "యాక్సెస్ షేర్ చేయడానికి మీ మొదటి నామినీని జోడించండి",
    
    // Time Capsule
    "timeCapsule.title": "టైమ్ క్యాప్సూల్",
    "timeCapsule.subtitle": "భవిష్యత్తు కోసం సందేశాలను షెడ్యూల్ చేయండి",
    "timeCapsule.create": "టైమ్ క్యాప్సూల్ సృష్టించు",
    "timeCapsule.edit": "టైమ్ క్యాప్సూల్ మార్చు",
    "timeCapsule.delete": "టైమ్ క్యాప్సూల్ తొలగించు",
    "timeCapsule.deleteConfirm": "మీరు ఈ టైమ్ క్యాప్సూల్‌ను తొలగించాలనుకుంటున్నారా?",
    "timeCapsule.messageTitle": "శీర్షిక",
    "timeCapsule.message": "సందేశం",
    "timeCapsule.recipientEmail": "గ్రహీత ఇమెయిల్",
    "timeCapsule.releaseDate": "విడుదల తేదీ",
    "timeCapsule.attachment": "అటాచ్‌మెంట్",
    "timeCapsule.addAttachment": "అటాచ్‌మెంట్ జోడించు",
    "timeCapsule.scheduled": "షెడ్యూల్ చేయబడింది",
    "timeCapsule.released": "విడుదలయింది",
    "timeCapsule.noCapsules": "టైమ్ క్యాప్సూల్స్ లేవు",
    "timeCapsule.createFirst": "మీ మొదటి టైమ్ క్యాప్సూల్ సృష్టించండి",
    
    // Profile
    "profile.title": "ప్రొఫైల్",
    "profile.subtitle": "మీ ప్రొఫైల్ నిర్వహించండి",
    "profile.edit": "ప్రొఫైల్ మార్చు",
    "profile.fullName": "పూర్తి పేరు",
    "profile.email": "ఇమెయిల్",
    "profile.phone": "ఫోన్",
    "profile.dateOfBirth": "పుట్టిన తేదీ",
    "profile.changePhoto": "ఫోటో మార్చు",
    "profile.updated": "ప్రొఫైల్ అప్డేట్ అయింది",
    
    // Settings page
    "settings.title": "సెట్టింగ్స్",
    "settings.subtitle": "మీ ప్రాధాన్యతలను నిర్వహించండి",
    "settings.changePassword": "పాస్‌వర్డ్ మార్చండి",
    "settings.changePassword.subtitle": "మీ పాస్‌వర్డ్‌ను అప్‌డేట్ చేయండి",
    "settings.emailPreferences": "ఇమెయిల్ ప్రాధాన్యతలు",
    "settings.emailPreferences.subtitle": "ఇమెయిల్ సెట్టింగ్స్ నిర్వహించండి",
    "settings.twoFactorAuth": "రెండు-కారక ప్రమాణీకరణ",
    "settings.twoFactorAuth.subtitle": "అదనపు భద్రత",
    "settings.twoFactorAuth.enabled": "ఆన్ చేయబడింది",
    "settings.appLock": "యాప్ లాక్",
    "settings.appLock.subtitle": "PIN లేదా బయోమెట్రిక్",
    "settings.appLock.active": "యాక్టివ్",
    "settings.activeSessions": "యాక్టివ్ సెషన్లు",
    "settings.activeSessions.subtitle": "లాగిన్ చేసిన పరికరాలను నిర్వహించండి",
    "settings.pushNotifications": "పుష్ నోటిఫికేషన్లు",
    "settings.pushNotifications.subtitle": "మొబైల్ అలర్ట్‌లు పొందండి",
    "settings.pushNotifications.mobileOnly": "మొబైల్ యాప్‌లో మాత్రమే అందుబాటులో ఉంటుంది",
    "settings.autoLockTimeout": "ఆటో లాక్ టైమ్‌అవుట్",
    "settings.backupRestore": "బ్యాకప్ & రీస్టోర్",
    "settings.backupRestore.subtitle": "మీ వాల్ట్‌ను ఎక్స్‌పోర్ట్ లేదా రీస్టోర్ చేయండి",
    "settings.helpSupport": "సహాయం & సపోర్ట్",
    "settings.helpSupport.subtitle": "FAQలు, గైడ్‌లు & సంప్రదించండి",
    "settings.language": "భాష",
    "settings.language.subtitle": "యాప్ భాషను మార్చండి",
    "settings.signOut": "సైన్ అవుట్",
    "settings.deleteAccount": "ఖాతాను తొలగించు",
    "settings.deleteAccount.title": "ఖాతాను తొలగించు",
    "settings.deleteAccount.description": "మీరు మీ ఖాతాను తొలగించాలనుకుంటున్నారా? ఈ చర్య రద్దు చేయబడదు.",
    "settings.deleteAccount.confirm": "ఖాతాను తొలగించు",
    "settings.deleting": "తొలగిస్తోంది...",
    "settings.appVersion": "యాప్ వెర్షన్ 2.0.0",
    
    // Language page
    "language.title": "భాష",
    "language.subtitle": "మీకు నచ్చిన భాషను ఎంచుకోండి",
    "language.current": "ప్రస్తుతం",
    
    // Auth
    "auth.signIn": "సైన్ ఇన్",
    "auth.signUp": "సైన్ అప్",
    "auth.signOut": "సైన్ అవుట్",
    "auth.email": "ఇమెయిల్",
    "auth.password": "పాస్‌వర్డ్",
    "auth.confirmPassword": "పాస్‌వర్డ్ నిర్ధారించండి",
    "auth.forgotPassword": "పాస్‌వర్డ్ మర్చిపోయారా?",
    "auth.resetPassword": "పాస్‌వర్డ్ రీసెట్",
    "auth.newPassword": "కొత్త పాస్‌వర్డ్",
    "auth.currentPassword": "ప్రస్తుత పాస్‌వర్డ్",
    "auth.createAccount": "ఖాతా సృష్టించండి",
    "auth.alreadyHaveAccount": "ఇప్పటికే ఖాతా ఉందా?",
    "auth.dontHaveAccount": "ఖాతా లేదా?",
    "auth.signInWithGoogle": "Google తో సైన్ ఇన్",
    "auth.signUpWithGoogle": "Google తో సైన్ అప్",
    "auth.orContinueWith": "లేదా కొనసాగించండి",
    "auth.enterOtp": "OTP నమోదు చేయండి",
    "auth.otpSent": "OTP మీ ఇమెయిల్‌కు పంపబడింది",
    "auth.verify": "ధృవీకరించు",
    "auth.resendOtp": "OTP మళ్ళీ పంపండి",
    
    // Notifications
    "notifications.title": "నోటిఫికేషన్లు",
    "notifications.noNotifications": "నోటిఫికేషన్లు లేవు",
    "notifications.markAsRead": "చదివినట్లు గుర్తు పెట్టు",
    "notifications.markAllRead": "అన్నీ చదివినట్లు గుర్తు పెట్టు",
    "notifications.clearAll": "అన్నీ క్లియర్ చేయండి",
    
    // Help Center
    "help.title": "సహాయం & సపోర్ట్",
    "help.subtitle": "మేము మీకు ఎలా సహాయం చేయగలం?",
    "help.faq": "తరచుగా అడిగే ప్రశ్నలు",
    "help.contact": "సపోర్ట్ సంప్రదించండి",
    "help.call": "కాల్",
    "help.email": "ఇమెయిల్",
    "help.whatsapp": "WhatsApp",
    "help.sendMessage": "సందేశం పంపండి",
    "help.yourMessage": "మీ సందేశం",
    
    // Toasts
    "toast.signedOut": "సైన్ అవుట్ అయింది",
    "toast.signedOut.description": "త్వరలో కలుద్దాం!",
    "toast.accountDeleted": "ఖాతా తొలగించబడింది",
    "toast.accountDeleted.description": "మీ ఖాతా శాశ్వతంగా తొలగించబడింది",
    "toast.deleteFailed": "తొలగించడం విఫలమైంది",
    "toast.error": "లోపం",
    "toast.pushEnabled": "పుష్ నోటిఫికేషన్లు ఆన్ చేయబడ్డాయి",
    "toast.pushEnabled.description": "మీరు ఈ పరికరంలో అలర్ట్‌లు పొందుతారు",
    "toast.pushDisabled": "పుష్ నోటిఫికేషన్లు ఆఫ్ చేయబడ్డాయి",
    "toast.permissionDenied": "అనుమతి నిరాకరించబడింది",
    "toast.permissionDenied.description": "దయచేసి మీ పరికర సెట్టింగ్స్‌లో నోటిఫికేషన్లను ఆన్ చేయండి",
    "toast.languageChanged": "భాష మార్చబడింది",
    "toast.saved": "సేవ్ అయింది",
    "toast.updated": "అప్డేట్ అయింది",
    "toast.deleted": "తొలగించబడింది",
    "toast.copied": "క్లిప్‌బోర్డ్‌కు కాపీ అయింది",
    "toast.uploadSuccess": "అప్లోడ్ విజయవంతం",
    "toast.uploadFailed": "అప్లోడ్ విఫలమైంది",
    "toast.downloadStarted": "డౌన్లోడ్ మొదలయింది",
    
    // Backup
    "backup.title": "బ్యాకప్ & రీస్టోర్",
    "backup.subtitle": "మీ డేటా బ్యాకప్‌లను నిర్వహించండి",
    "backup.create": "బ్యాకప్ సృష్టించు",
    "backup.restore": "బ్యాకప్ రీస్టోర్",
    "backup.history": "బ్యాకప్ చరిత్ర",
    "backup.frequency": "బ్యాకప్ ఫ్రీక్వెన్సీ",
    "backup.lastBackup": "చివరి బ్యాకప్",
    "backup.noBackups": "బ్యాకప్‌లు లేవు",
    
    // Security
    "security.twoFactor": "రెండు-కారక ప్రమాణీకరణ",
    "security.biometric": "బయోమెట్రిక్ లాగిన్",
    "security.appLock": "యాప్ లాక్",
    "security.pinLock": "PIN లాక్",
    "security.setupPin": "PIN సెటప్ చేయండి",
    "security.enterPin": "PIN నమోదు చేయండి",
    "security.confirmPin": "PIN నిర్ధారించండి",
    "security.wrongPin": "తప్పు PIN",
    "security.pinMismatch": "PINలు సరిపోలలేదు",
    "security.pinSet": "PIN విజయవంతంగా సెట్ అయింది",
    
    // Inactivity
    "inactivity.title": "నిష్క్రియాత్మక ట్రిగ్గర్",
    "inactivity.subtitle": "అత్యవసర యాక్సెస్ సెటప్ చేయండి",
    "inactivity.threshold": "నిష్క్రియాత్మక పరిమితి",
    "inactivity.days": "రోజులు",
    "inactivity.message": "అనుకూల సందేశం",
    "inactivity.enabled": "ట్రిగ్గర్ ఆన్",
    "inactivity.disabled": "ట్రిగ్గర్ ఆఫ్",
    
    // Access Control
    "access.manageAccess": "యాక్సెస్ నిర్వహించు",
    "access.grantAccess": "యాక్సెస్ ఇవ్వండి",
    "access.revokeAccess": "యాక్సెస్ రద్దు చేయండి",
    "access.viewOnly": "చూడటం మాత్రమే",
    "access.downloadOnly": "డౌన్లోడ్ మాత్రమే",
    "access.viewAndDownload": "చూడటం & డౌన్లోడ్",
    "access.selectNominee": "నామినీ ఎంచుకోండి",
    "access.accessLevel": "యాక్సెస్ స్థాయి",
    "access.noAccess": "యాక్సెస్ ఇవ్వలేదు",
  },
  kn: {
    // Common
    "common.welcome": "ಸ್ವಾಗತ",
    "common.enabled": "ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ",
    "common.disabled": "ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ",
    "common.minutes": "ನಿಮಿಷಗಳು",
    "common.minute": "ನಿಮಿಷ",
    "common.save": "ಉಳಿಸಿ",
    "common.cancel": "ರದ್ದುಮಾಡಿ",
    "common.delete": "ಅಳಿಸಿ",
    "common.edit": "ತಿದ್ದು",
    "common.add": "ಸೇರಿಸಿ",
    "common.search": "ಹುಡುಕಿ",
    "common.loading": "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    "common.error": "ದೋಷ",
    "common.success": "ಯಶಸ್ಸು",
    "common.confirm": "ದೃಢೀಕರಿಸಿ",
    "common.back": "ಹಿಂದೆ",
    "common.next": "ಮುಂದೆ",
    "common.done": "ಮುಗಿಯಿತು",
    "common.close": "ಮುಚ್ಚಿ",
    "common.yes": "ಹೌದು",
    "common.no": "ಇಲ್ಲ",
    "common.ok": "ಸರಿ",
    "common.documents": "ಡಾಕ್ಯುಮೆಂಟ್‌ಗಳು",
    "common.document": "ಡಾಕ್ಯುಮೆಂಟ್",
    "common.noResults": "ಫಲಿತಾಂಶಗಳಿಲ್ಲ",
    "common.tryAgain": "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
    "common.view": "ನೋಡಿ",
    "common.download": "ಡೌನ್‌ಲೋಡ್",
    "common.upload": "ಅಪ್‌ಲೋಡ್",
    "common.create": "ರಚಿಸಿ",
    "common.update": "ನವೀಕರಿಸಿ",
    "common.remove": "ತೆಗೆದುಹಾಕಿ",
    
    // Navigation
    "nav.home": "ಮುಖಪುಟ",
    "nav.vault": "ವಾಲ್ಟ್",
    "nav.settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    
    // Dashboard
    "dashboard.welcome": "ಸ್ವಾಗತ,",
    "dashboard.securityScore": "ಭದ್ರತಾ ಸ್ಕೋರ್",
    "dashboard.docs": "ಡಾಕ್ಸ್",
    "dashboard.nominees": "ನಾಮಿನಿಗಳು",
    "dashboard.capsules": "ಕ್ಯಾಪ್ಸೂಲ್‌ಗಳು",
    "dashboard.trigger": "ಟ್ರಿಗ್ಗರ್",
    "dashboard.quickActions": "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
    "dashboard.noQuickActions": "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು ಸಕ್ರಿಯವಾಗಿಲ್ಲ",
    "dashboard.triggerEnabled": "ಟ್ರಿಗ್ಗರ್ ಸಕ್ರಿಯವಾಗಿದೆ",
    "dashboard.triggerDisabled": "ಟ್ರಿಗ್ಗರ್ ನಿಷ್ಕ್ರಿಯವಾಗಿದೆ",
    
    // Vault
    "vault.title": "ನನ್ನ ವಾಲ್ಟ್",
    "vault.documents": "ಡಾಕ್ಯುಮೆಂಟ್‌ಗಳು",
    "vault.searchPlaceholder": "ಡಾಕ್ಯುಮೆಂಟ್‌ಗಳು, ವರ್ಗಗಳನ್ನು ಹುಡುಕಿ...",
    "vault.resultsFound": "{count} ಫಲಿತಾಂಶಗಳು ಕಂಡುಬಂದಿವೆ",
    "vault.noResults": "ಫಲಿತಾಂಶಗಳಿಲ್ಲ",
    "vault.noResultsDesc": "ನಿಮ್ಮ ಹುಡುಕಾಟವನ್ನು ಸರಿಹೊಂದಿಸಿ ಅಥವಾ ಎಲ್ಲಾ ವರ್ಗಗಳನ್ನು ನೋಡಿ",
    "vault.clearSearch": "ಹುಡುಕಾಟ ತೆರವುಗೊಳಿಸಿ",
    "vault.addCategory": "ವರ್ಗ ಸೇರಿಸಿ",
    "vault.categoryName": "ವರ್ಗ ಹೆಸರು",
    "vault.categoryNamePlaceholder": "ವರ್ಗ ಹೆಸರು ನಮೂದಿಸಿ",
    "vault.createCategory": "ವರ್ಗ ರಚಿಸಿ",
    "vault.deleteCategory": "ವರ್ಗ ಅಳಿಸಿ",
    "vault.deleteCategoryConfirm": "ನೀವು ಈ ವರ್ಗವನ್ನು ಅಳಿಸಲು ಖಚಿತವಾಗಿದ್ದೀರಾ?",
    "vault.categoryCreated": "ವರ್ಗ ರಚಿಸಲಾಗಿದೆ!",
    "vault.categoryDeleted": "ವರ್ಗ ಅಳಿಸಲಾಗಿದೆ",
    "vault.cannotDelete": "ಅಳಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ",
    "vault.defaultCategoryError": "ಡೀಫಾಲ್ಟ್ ವರ್ಗಗಳನ್ನು ಅಳಿಸಲಾಗುವುದಿಲ್ಲ",
    "vault.noDocuments": "ಡಾಕ್ಯುಮೆಂಟ್‌ಗಳಿಲ್ಲ",
    "vault.uploadFirst": "ನಿಮ್ಮ ಮೊದಲ ಡಾಕ್ಯುಮೆಂಟ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    "vault.manageAccess": "ಪ್ರವೇಶ ನಿರ್ವಹಿಸಿ",
    "vault.whoHasAccess": "ಯಾರಿಗೆ ಪ್ರವೇಶವಿದೆ",
    "vault.matches": "ಹೊಂದಾಣಿಕೆಗಳು",
    "vault.match": "ಹೊಂದಾಣಿಕೆ",
    
    // Documents
    "document.upload": "ಡಾಕ್ಯುಮೆಂಟ್ ಅಪ್‌ಲೋಡ್",
    "document.view": "ಡಾಕ್ಯುಮೆಂಟ್ ನೋಡಿ",
    "document.download": "ಡೌನ್‌ಲೋಡ್",
    "document.delete": "ಡಾಕ್ಯುಮೆಂಟ್ ಅಳಿಸಿ",
    "document.deleteConfirm": "ನೀವು ಈ ಡಾಕ್ಯುಮೆಂಟ್ ಅನ್ನು ಅಳಿಸಲು ಖಚಿತವಾಗಿದ್ದೀರಾ?",
    "document.uploaded": "ಡಾಕ್ಯುಮೆಂಟ್ ಅಪ್‌ಲೋಡ್ ಆಯಿತು",
    "document.deleted": "ಡಾಕ್ಯುಮೆಂಟ್ ಅಳಿಸಲಾಗಿದೆ",
    "document.lock": "ಡಾಕ್ಯುಮೆಂಟ್ ಲಾಕ್ ಮಾಡಿ",
    "document.unlock": "ಡಾಕ್ಯುಮೆಂಟ್ ಅನ್‌ಲಾಕ್ ಮಾಡಿ",
    "document.password": "ಪಾಸ್‌ವರ್ಡ್",
    "document.confirmPassword": "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
    "document.fromDevice": "ಸಾಧನದಿಂದ",
    "document.fromGoogleDrive": "Google Drive ನಿಂದ",
    "document.scanDocument": "ಡಾಕ್ಯುಮೆಂಟ್ ಸ್ಕ್ಯಾನ್",
    "document.maxSize": "ಗರಿಷ್ಠ ಫೈಲ್ ಗಾತ್ರ: 20MB",
    
    // Nominees
    "nominee.title": "ನಾಮಿನಿಗಳು",
    "nominee.subtitle": "ನಿಮ್ಮ ವಿಶ್ವಾಸಾರ್ಹ ಸಂಪರ್ಕಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    "nominee.add": "ನಾಮಿನಿ ಸೇರಿಸಿ",
    "nominee.edit": "ನಾಮಿನಿ ತಿದ್ದು",
    "nominee.delete": "ನಾಮಿನಿ ಅಳಿಸಿ",
    "nominee.deleteConfirm": "ನೀವು ಈ ನಾಮಿನಿಯನ್ನು ತೆಗೆದುಹಾಕಲು ಖಚಿತವಾಗಿದ್ದೀರಾ?",
    "nominee.fullName": "ಪೂರ್ಣ ಹೆಸರು",
    "nominee.email": "ಇಮೇಲ್",
    "nominee.phone": "ಫೋನ್",
    "nominee.relation": "ಸಂಬಂಧ",
    "nominee.pending": "ಬಾಕಿ ಇದೆ",
    "nominee.verified": "ದೃಢೀಕರಿಸಲಾಗಿದೆ",
    "nominee.sendVerification": "ದೃಢೀಕರಣ ಕಳುಹಿಸಿ",
    "nominee.resendVerification": "ದೃಢೀಕರಣ ಮತ್ತೆ ಕಳುಹಿಸಿ",
    "nominee.noNominees": "ನಾಮಿನಿಗಳಿಲ್ಲ",
    "nominee.addFirst": "ಪ್ರವೇಶ ಹಂಚಲು ನಿಮ್ಮ ಮೊದಲ ನಾಮಿನಿಯನ್ನು ಸೇರಿಸಿ",
    
    // Time Capsule
    "timeCapsule.title": "ಟೈಮ್ ಕ್ಯಾಪ್ಸೂಲ್",
    "timeCapsule.subtitle": "ಭವಿಷ್ಯಕ್ಕಾಗಿ ಸಂದೇಶಗಳನ್ನು ಶೆಡ್ಯೂಲ್ ಮಾಡಿ",
    "timeCapsule.create": "ಟೈಮ್ ಕ್ಯಾಪ್ಸೂಲ್ ರಚಿಸಿ",
    "timeCapsule.edit": "ಟೈಮ್ ಕ್ಯಾಪ್ಸೂಲ್ ತಿದ್ದು",
    "timeCapsule.delete": "ಟೈಮ್ ಕ್ಯಾಪ್ಸೂಲ್ ಅಳಿಸಿ",
    "timeCapsule.deleteConfirm": "ನೀವು ಈ ಟೈಮ್ ಕ್ಯಾಪ್ಸೂಲ್ ಅನ್ನು ಅಳಿಸಲು ಖಚಿತವಾಗಿದ್ದೀರಾ?",
    "timeCapsule.messageTitle": "ಶೀರ್ಷಿಕೆ",
    "timeCapsule.message": "ಸಂದೇಶ",
    "timeCapsule.recipientEmail": "ಸ್ವೀಕೃತದಾರ ಇಮೇಲ್",
    "timeCapsule.releaseDate": "ಬಿಡುಗಡೆ ದಿನಾಂಕ",
    "timeCapsule.attachment": "ಲಗತ್ತು",
    "timeCapsule.addAttachment": "ಲಗತ್ತು ಸೇರಿಸಿ",
    "timeCapsule.scheduled": "ಶೆಡ್ಯೂಲ್ ಆಗಿದೆ",
    "timeCapsule.released": "ಬಿಡುಗಡೆಯಾಗಿದೆ",
    "timeCapsule.noCapsules": "ಟೈಮ್ ಕ್ಯಾಪ್ಸೂಲ್‌ಗಳಿಲ್ಲ",
    "timeCapsule.createFirst": "ನಿಮ್ಮ ಮೊದಲ ಟೈಮ್ ಕ್ಯಾಪ್ಸೂಲ್ ರಚಿಸಿ",
    
    // Profile
    "profile.title": "ಪ್ರೊಫೈಲ್",
    "profile.subtitle": "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ನಿರ್ವಹಿಸಿ",
    "profile.edit": "ಪ್ರೊಫೈಲ್ ತಿದ್ದು",
    "profile.fullName": "ಪೂರ್ಣ ಹೆಸರು",
    "profile.email": "ಇಮೇಲ್",
    "profile.phone": "ಫೋನ್",
    "profile.dateOfBirth": "ಹುಟ್ಟಿದ ದಿನಾಂಕ",
    "profile.changePhoto": "ಫೋಟೋ ಬದಲಾಯಿಸಿ",
    "profile.updated": "ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಲಾಗಿದೆ",
    
    // Settings page
    "settings.title": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    "settings.subtitle": "ನಿಮ್ಮ ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    "settings.changePassword": "ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ",
    "settings.changePassword.subtitle": "ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ಅಪ್‌ಡೇಟ್ ಮಾಡಿ",
    "settings.emailPreferences": "ಇಮೇಲ್ ಆದ್ಯತೆಗಳು",
    "settings.emailPreferences.subtitle": "ಇಮೇಲ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    "settings.twoFactorAuth": "ಎರಡು-ಅಂಶ ದೃಢೀಕರಣ",
    "settings.twoFactorAuth.subtitle": "ಹೆಚ್ಚುವರಿ ಭದ್ರತೆ",
    "settings.twoFactorAuth.enabled": "ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ",
    "settings.appLock": "ಆ್ಯಪ್ ಲಾಕ್",
    "settings.appLock.subtitle": "PIN ಅಥವಾ ಬಯೋಮೆಟ್ರಿಕ್",
    "settings.appLock.active": "ಸಕ್ರಿಯ",
    "settings.activeSessions": "ಸಕ್ರಿಯ ಸೆಷನ್‌ಗಳು",
    "settings.activeSessions.subtitle": "ಲಾಗಿನ್ ಆದ ಸಾಧನಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    "settings.pushNotifications": "ಪುಶ್ ಅಧಿಸೂಚನೆಗಳು",
    "settings.pushNotifications.subtitle": "ಮೊಬೈಲ್ ಎಚ್ಚರಿಕೆಗಳನ್ನು ಪಡೆಯಿರಿ",
    "settings.pushNotifications.mobileOnly": "ಮೊಬೈಲ್ ಆ್ಯಪ್‌ನಲ್ಲಿ ಮಾತ್ರ ಲಭ್ಯವಿದೆ",
    "settings.autoLockTimeout": "ಆಟೋ ಲಾಕ್ ಟೈಮ್‌ಔಟ್",
    "settings.backupRestore": "ಬ್ಯಾಕಪ್ & ಮರುಸ್ಥಾಪನೆ",
    "settings.backupRestore.subtitle": "ನಿಮ್ಮ ವಾಲ್ಟ್ ಅನ್ನು ರಫ್ತು ಅಥವಾ ಮರುಸ್ಥಾಪಿಸಿ",
    "settings.helpSupport": "ಸಹಾಯ & ಬೆಂಬಲ",
    "settings.helpSupport.subtitle": "FAQಗಳು, ಮಾರ್ಗದರ್ಶಿಗಳು & ಸಂಪರ್ಕ",
    "settings.language": "ಭಾಷೆ",
    "settings.language.subtitle": "ಆ್ಯಪ್ ಭಾಷೆಯನ್ನು ಬದಲಾಯಿಸಿ",
    "settings.signOut": "ಸೈನ್ ಔಟ್",
    "settings.deleteAccount": "ಖಾತೆ ಅಳಿಸಿ",
    "settings.deleteAccount.title": "ಖಾತೆ ಅಳಿಸಿ",
    "settings.deleteAccount.description": "ನೀವು ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಅಳಿಸಲು ಖಚಿತವಾಗಿದ್ದೀರಾ?",
    "settings.deleteAccount.confirm": "ಖಾತೆ ಅಳಿಸಿ",
    "settings.deleting": "ಅಳಿಸಲಾಗುತ್ತಿದೆ...",
    "settings.appVersion": "ಆ್ಯಪ್ ಆವೃತ್ತಿ 2.0.0",
    
    // Language page
    "language.title": "ಭಾಷೆ",
    "language.subtitle": "ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆರಿಸಿ",
    "language.current": "ಪ್ರಸ್ತುತ",
    
    // Auth
    "auth.signIn": "ಸೈನ್ ಇನ್",
    "auth.signUp": "ಸೈನ್ ಅಪ್",
    "auth.signOut": "ಸೈನ್ ಔಟ್",
    "auth.email": "ಇಮೇಲ್",
    "auth.password": "ಪಾಸ್‌ವರ್ಡ್",
    "auth.confirmPassword": "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
    "auth.forgotPassword": "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?",
    "auth.resetPassword": "ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಸಿ",
    "auth.newPassword": "ಹೊಸ ಪಾಸ್‌ವರ್ಡ್",
    "auth.currentPassword": "ಪ್ರಸ್ತುತ ಪಾಸ್‌ವರ್ಡ್",
    "auth.createAccount": "ಖಾತೆ ರಚಿಸಿ",
    "auth.alreadyHaveAccount": "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?",
    "auth.dontHaveAccount": "ಖಾತೆ ಇಲ್ಲವೇ?",
    "auth.signInWithGoogle": "Google ನೊಂದಿಗೆ ಸೈನ್ ಇನ್",
    "auth.signUpWithGoogle": "Google ನೊಂದಿಗೆ ಸೈನ್ ಅಪ್",
    "auth.orContinueWith": "ಅಥವಾ ಮುಂದುವರಿಸಿ",
    "auth.enterOtp": "OTP ನಮೂದಿಸಿ",
    "auth.otpSent": "OTP ನಿಮ್ಮ ಇಮೇಲ್‌ಗೆ ಕಳುಹಿಸಲಾಗಿದೆ",
    "auth.verify": "ದೃಢೀಕರಿಸಿ",
    "auth.resendOtp": "OTP ಮತ್ತೆ ಕಳುಹಿಸಿ",
    
    // Notifications
    "notifications.title": "ಅಧಿಸೂಚನೆಗಳು",
    "notifications.noNotifications": "ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ",
    "notifications.markAsRead": "ಓದಿದಂತೆ ಗುರುತಿಸಿ",
    "notifications.markAllRead": "ಎಲ್ಲವನ್ನೂ ಓದಿದಂತೆ ಗುರುತಿಸಿ",
    "notifications.clearAll": "ಎಲ್ಲವನ್ನೂ ತೆರವುಗೊಳಿಸಿ",
    
    // Help Center
    "help.title": "ಸಹಾಯ & ಬೆಂಬಲ",
    "help.subtitle": "ನಾವು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?",
    "help.faq": "ಆಗಾಗ್ಗೆ ಕೇಳುವ ಪ್ರಶ್ನೆಗಳು",
    "help.contact": "ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಿ",
    "help.call": "ಕರೆ",
    "help.email": "ಇಮೇಲ್",
    "help.whatsapp": "WhatsApp",
    "help.sendMessage": "ಸಂದೇಶ ಕಳುಹಿಸಿ",
    "help.yourMessage": "ನಿಮ್ಮ ಸಂದೇಶ",
    
    // Toasts
    "toast.signedOut": "ಸೈನ್ ಔಟ್ ಆಯಿತು",
    "toast.signedOut.description": "ಶೀಘ್ರದಲ್ಲಿ ಭೇಟಿಯಾಗೋಣ!",
    "toast.accountDeleted": "ಖಾತೆ ಅಳಿಸಲಾಗಿದೆ",
    "toast.accountDeleted.description": "ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಲಾಗಿದೆ",
    "toast.deleteFailed": "ಅಳಿಸುವಿಕೆ ವಿಫಲವಾಯಿತು",
    "toast.error": "ದೋಷ",
    "toast.pushEnabled": "ಪುಶ್ ಅಧಿಸೂಚನೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ",
    "toast.pushEnabled.description": "ನೀವು ಈ ಸಾಧನದಲ್ಲಿ ಎಚ್ಚರಿಕೆಗಳನ್ನು ಸ್ವೀಕರಿಸುತ್ತೀರಿ",
    "toast.pushDisabled": "ಪುಶ್ ಅಧಿಸೂಚನೆಗಳನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ",
    "toast.permissionDenied": "ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ",
    "toast.permissionDenied.description": "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಸಾಧನ ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಅಧಿಸೂಚನೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ",
    "toast.languageChanged": "ಭಾಷೆ ಬದಲಾಯಿಸಲಾಗಿದೆ",
    "toast.saved": "ಉಳಿಸಲಾಗಿದೆ",
    "toast.updated": "ನವೀಕರಿಸಲಾಗಿದೆ",
    "toast.deleted": "ಅಳಿಸಲಾಗಿದೆ",
    "toast.copied": "ಕ್ಲಿಪ್‌ಬೋರ್ಡ್‌ಗೆ ನಕಲಿಸಲಾಗಿದೆ",
    "toast.uploadSuccess": "ಅಪ್‌ಲೋಡ್ ಯಶಸ್ವಿ",
    "toast.uploadFailed": "ಅಪ್‌ಲೋಡ್ ವಿಫಲ",
    "toast.downloadStarted": "ಡೌನ್‌ಲೋಡ್ ಪ್ರಾರಂಭವಾಯಿತು",
    
    // Backup
    "backup.title": "ಬ್ಯಾಕಪ್ & ಮರುಸ್ಥಾಪನೆ",
    "backup.subtitle": "ನಿಮ್ಮ ಡೇಟಾ ಬ್ಯಾಕಪ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    "backup.create": "ಬ್ಯಾಕಪ್ ರಚಿಸಿ",
    "backup.restore": "ಬ್ಯಾಕಪ್ ಮರುಸ್ಥಾಪಿಸಿ",
    "backup.history": "ಬ್ಯಾಕಪ್ ಇತಿಹಾಸ",
    "backup.frequency": "ಬ್ಯಾಕಪ್ ಆವರ್ತನ",
    "backup.lastBackup": "ಕೊನೆಯ ಬ್ಯಾಕಪ್",
    "backup.noBackups": "ಬ್ಯಾಕಪ್‌ಗಳಿಲ್ಲ",
    
    // Security
    "security.twoFactor": "ಎರಡು-ಅಂಶ ದೃಢೀಕರಣ",
    "security.biometric": "ಬಯೋಮೆಟ್ರಿಕ್ ಲಾಗಿನ್",
    "security.appLock": "ಆ್ಯಪ್ ಲಾಕ್",
    "security.pinLock": "PIN ಲಾಕ್",
    "security.setupPin": "PIN ಸೆಟಪ್ ಮಾಡಿ",
    "security.enterPin": "PIN ನಮೂದಿಸಿ",
    "security.confirmPin": "PIN ದೃಢೀಕರಿಸಿ",
    "security.wrongPin": "ತಪ್ಪು PIN",
    "security.pinMismatch": "PIN ಹೊಂದುತ್ತಿಲ್ಲ",
    "security.pinSet": "PIN ಯಶಸ್ವಿಯಾಗಿ ಸೆಟ್ ಆಯಿತು",
    
    // Inactivity
    "inactivity.title": "ನಿಷ್ಕ್ರಿಯತೆ ಟ್ರಿಗ್ಗರ್",
    "inactivity.subtitle": "ತುರ್ತು ಪ್ರವೇಶ ಸೆಟಪ್ ಮಾಡಿ",
    "inactivity.threshold": "ನಿಷ್ಕ್ರಿಯತೆ ಮಿತಿ",
    "inactivity.days": "ದಿನಗಳು",
    "inactivity.message": "ಕಸ್ಟಮ್ ಸಂದೇಶ",
    "inactivity.enabled": "ಟ್ರಿಗ್ಗರ್ ಸಕ್ರಿಯ",
    "inactivity.disabled": "ಟ್ರಿಗ್ಗರ್ ನಿಷ್ಕ್ರಿಯ",
    
    // Access Control
    "access.manageAccess": "ಪ್ರವೇಶ ನಿರ್ವಹಿಸಿ",
    "access.grantAccess": "ಪ್ರವೇಶ ನೀಡಿ",
    "access.revokeAccess": "ಪ್ರವೇಶ ಹಿಂಪಡೆಯಿರಿ",
    "access.viewOnly": "ನೋಡುವುದು ಮಾತ್ರ",
    "access.downloadOnly": "ಡೌನ್‌ಲೋಡ್ ಮಾತ್ರ",
    "access.viewAndDownload": "ನೋಡುವುದು & ಡೌನ್‌ಲೋಡ್",
    "access.selectNominee": "ನಾಮಿನಿ ಆರಿಸಿ",
    "access.accessLevel": "ಪ್ರವೇಶ ಹಂತ",
    "access.noAccess": "ಪ್ರವೇಶ ನೀಡಿಲ್ಲ",
  },
  hi: {
    // Common
    "common.welcome": "स्वागत",
    "common.enabled": "सक्षम",
    "common.disabled": "अक्षम",
    "common.minutes": "मिनट",
    "common.minute": "मिनट",
    "common.save": "सेव करें",
    "common.cancel": "रद्द करें",
    "common.delete": "हटाएं",
    "common.edit": "संपादित करें",
    "common.add": "जोड़ें",
    "common.search": "खोजें",
    "common.loading": "लोड हो रहा है...",
    "common.error": "त्रुटि",
    "common.success": "सफलता",
    "common.confirm": "पुष्टि करें",
    "common.back": "वापस",
    "common.next": "आगे",
    "common.done": "हो गया",
    "common.close": "बंद करें",
    "common.yes": "हां",
    "common.no": "नहीं",
    "common.ok": "ठीक है",
    "common.documents": "दस्तावेज़",
    "common.document": "दस्तावेज़",
    "common.noResults": "कोई परिणाम नहीं",
    "common.tryAgain": "फिर से प्रयास करें",
    "common.view": "देखें",
    "common.download": "डाउनलोड",
    "common.upload": "अपलोड",
    "common.create": "बनाएं",
    "common.update": "अपडेट",
    "common.remove": "हटाएं",
    
    // Navigation
    "nav.home": "होम",
    "nav.vault": "वॉल्ट",
    "nav.settings": "सेटिंग्स",
    
    // Dashboard
    "dashboard.welcome": "स्वागत,",
    "dashboard.securityScore": "सुरक्षा स्कोर",
    "dashboard.docs": "डॉक्स",
    "dashboard.nominees": "नामिनी",
    "dashboard.capsules": "कैप्सूल",
    "dashboard.trigger": "ट्रिगर",
    "dashboard.quickActions": "त्वरित क्रियाएं",
    "dashboard.noQuickActions": "कोई त्वरित क्रियाएं सक्षम नहीं",
    "dashboard.triggerEnabled": "ट्रिगर सक्षम है",
    "dashboard.triggerDisabled": "ट्रिगर अक्षम है",
    
    // Vault
    "vault.title": "मेरा वॉल्ट",
    "vault.documents": "दस्तावेज़",
    "vault.searchPlaceholder": "दस्तावेज़, श्रेणियां खोजें...",
    "vault.resultsFound": "{count} परिणाम मिले",
    "vault.noResults": "कोई परिणाम नहीं",
    "vault.noResultsDesc": "अपनी खोज समायोजित करें या सभी श्रेणियां देखें",
    "vault.clearSearch": "खोज साफ़ करें",
    "vault.addCategory": "श्रेणी जोड़ें",
    "vault.categoryName": "श्रेणी नाम",
    "vault.categoryNamePlaceholder": "श्रेणी नाम दर्ज करें",
    "vault.createCategory": "श्रेणी बनाएं",
    "vault.deleteCategory": "श्रेणी हटाएं",
    "vault.deleteCategoryConfirm": "क्या आप वाकई इस श्रेणी को हटाना चाहते हैं?",
    "vault.categoryCreated": "श्रेणी बनाई गई!",
    "vault.categoryDeleted": "श्रेणी हटाई गई",
    "vault.cannotDelete": "हटा नहीं सकते",
    "vault.defaultCategoryError": "डिफ़ॉल्ट श्रेणियां नहीं हटाई जा सकतीं",
    "vault.noDocuments": "कोई दस्तावेज़ नहीं",
    "vault.uploadFirst": "अपना पहला दस्तावेज़ अपलोड करें",
    "vault.manageAccess": "पहुंच प्रबंधित करें",
    "vault.whoHasAccess": "किसकी पहुंच है",
    "vault.matches": "मैच",
    "vault.match": "मैच",
    
    // Documents
    "document.upload": "दस्तावेज़ अपलोड",
    "document.view": "दस्तावेज़ देखें",
    "document.download": "डाउनलोड",
    "document.delete": "दस्तावेज़ हटाएं",
    "document.deleteConfirm": "क्या आप वाकई इस दस्तावेज़ को हटाना चाहते हैं?",
    "document.uploaded": "दस्तावेज़ अपलोड हुआ",
    "document.deleted": "दस्तावेज़ हटाया गया",
    "document.lock": "दस्तावेज़ लॉक करें",
    "document.unlock": "दस्तावेज़ अनलॉक करें",
    "document.password": "पासवर्ड",
    "document.confirmPassword": "पासवर्ड पुष्टि करें",
    "document.fromDevice": "डिवाइस से",
    "document.fromGoogleDrive": "Google Drive से",
    "document.scanDocument": "दस्तावेज़ स्कैन",
    "document.maxSize": "अधिकतम फ़ाइल आकार: 20MB",
    
    // Nominees
    "nominee.title": "नामिनी",
    "nominee.subtitle": "अपने विश्वसनीय संपर्कों को प्रबंधित करें",
    "nominee.add": "नामिनी जोड़ें",
    "nominee.edit": "नामिनी संपादित करें",
    "nominee.delete": "नामिनी हटाएं",
    "nominee.deleteConfirm": "क्या आप वाकई इस नामिनी को हटाना चाहते हैं?",
    "nominee.fullName": "पूरा नाम",
    "nominee.email": "ईमेल",
    "nominee.phone": "फोन",
    "nominee.relation": "संबंध",
    "nominee.pending": "लंबित",
    "nominee.verified": "सत्यापित",
    "nominee.sendVerification": "सत्यापन भेजें",
    "nominee.resendVerification": "सत्यापन फिर से भेजें",
    "nominee.noNominees": "कोई नामिनी नहीं जोड़ा गया",
    "nominee.addFirst": "पहुंच साझा करने के लिए अपना पहला नामिनी जोड़ें",
    
    // Time Capsule
    "timeCapsule.title": "टाइम कैप्सूल",
    "timeCapsule.subtitle": "भविष्य के लिए संदेश शेड्यूल करें",
    "timeCapsule.create": "टाइम कैप्सूल बनाएं",
    "timeCapsule.edit": "टाइम कैप्सूल संपादित करें",
    "timeCapsule.delete": "टाइम कैप्सूल हटाएं",
    "timeCapsule.deleteConfirm": "क्या आप वाकई इस टाइम कैप्सूल को हटाना चाहते हैं?",
    "timeCapsule.messageTitle": "शीर्षक",
    "timeCapsule.message": "संदेश",
    "timeCapsule.recipientEmail": "प्राप्तकर्ता ईमेल",
    "timeCapsule.releaseDate": "रिलीज़ तिथि",
    "timeCapsule.attachment": "अटैचमेंट",
    "timeCapsule.addAttachment": "अटैचमेंट जोड़ें",
    "timeCapsule.scheduled": "शेड्यूल किया गया",
    "timeCapsule.released": "रिलीज़ हुआ",
    "timeCapsule.noCapsules": "कोई टाइम कैप्सूल नहीं",
    "timeCapsule.createFirst": "अपना पहला टाइम कैप्सूल बनाएं",
    
    // Profile
    "profile.title": "प्रोफाइल",
    "profile.subtitle": "अपनी प्रोफाइल प्रबंधित करें",
    "profile.edit": "प्रोफाइल संपादित करें",
    "profile.fullName": "पूरा नाम",
    "profile.email": "ईमेल",
    "profile.phone": "फोन",
    "profile.dateOfBirth": "जन्म तिथि",
    "profile.changePhoto": "फोटो बदलें",
    "profile.updated": "प्रोफाइल अपडेट हुई",
    
    // Settings page
    "settings.title": "सेटिंग्स",
    "settings.subtitle": "अपनी प्राथमिकताएं प्रबंधित करें",
    "settings.changePassword": "पासवर्ड बदलें",
    "settings.changePassword.subtitle": "अपना पासवर्ड अपडेट करें",
    "settings.emailPreferences": "ईमेल प्राथमिकताएं",
    "settings.emailPreferences.subtitle": "ईमेल सेटिंग्स प्रबंधित करें",
    "settings.twoFactorAuth": "दो-कारक प्रमाणीकरण",
    "settings.twoFactorAuth.subtitle": "अतिरिक्त सुरक्षा",
    "settings.twoFactorAuth.enabled": "सक्षम",
    "settings.appLock": "ऐप लॉक",
    "settings.appLock.subtitle": "PIN या बायोमेट्रिक",
    "settings.appLock.active": "सक्रिय",
    "settings.activeSessions": "सक्रिय सत्र",
    "settings.activeSessions.subtitle": "लॉग इन डिवाइस प्रबंधित करें",
    "settings.pushNotifications": "पुश नोटिफिकेशन",
    "settings.pushNotifications.subtitle": "मोबाइल अलर्ट प्राप्त करें",
    "settings.pushNotifications.mobileOnly": "केवल मोबाइल ऐप पर उपलब्ध",
    "settings.autoLockTimeout": "ऑटो लॉक टाइमआउट",
    "settings.backupRestore": "बैकअप और रिस्टोर",
    "settings.backupRestore.subtitle": "अपनी वॉल्ट निर्यात या पुनर्स्थापित करें",
    "settings.helpSupport": "सहायता और समर्थन",
    "settings.helpSupport.subtitle": "FAQs, गाइड और संपर्क",
    "settings.language": "भाषा",
    "settings.language.subtitle": "ऐप की भाषा बदलें",
    "settings.signOut": "साइन आउट",
    "settings.deleteAccount": "खाता हटाएं",
    "settings.deleteAccount.title": "खाता हटाएं",
    "settings.deleteAccount.description": "क्या आप वाकई अपना खाता हटाना चाहते हैं?",
    "settings.deleteAccount.confirm": "खाता हटाएं",
    "settings.deleting": "हटाया जा रहा है...",
    "settings.appVersion": "ऐप संस्करण 2.0.0",
    
    // Language page
    "language.title": "भाषा",
    "language.subtitle": "अपनी पसंदीदा भाषा चुनें",
    "language.current": "वर्तमान",
    
    // Auth
    "auth.signIn": "साइन इन",
    "auth.signUp": "साइन अप",
    "auth.signOut": "साइन आउट",
    "auth.email": "ईमेल",
    "auth.password": "पासवर्ड",
    "auth.confirmPassword": "पासवर्ड पुष्टि करें",
    "auth.forgotPassword": "पासवर्ड भूल गए?",
    "auth.resetPassword": "पासवर्ड रीसेट",
    "auth.newPassword": "नया पासवर्ड",
    "auth.currentPassword": "वर्तमान पासवर्ड",
    "auth.createAccount": "खाता बनाएं",
    "auth.alreadyHaveAccount": "पहले से खाता है?",
    "auth.dontHaveAccount": "खाता नहीं है?",
    "auth.signInWithGoogle": "Google से साइन इन",
    "auth.signUpWithGoogle": "Google से साइन अप",
    "auth.orContinueWith": "या जारी रखें",
    "auth.enterOtp": "OTP दर्ज करें",
    "auth.otpSent": "OTP आपके ईमेल पर भेजा गया",
    "auth.verify": "सत्यापित करें",
    "auth.resendOtp": "OTP फिर से भेजें",
    
    // Notifications
    "notifications.title": "सूचनाएं",
    "notifications.noNotifications": "कोई सूचनाएं नहीं",
    "notifications.markAsRead": "पढ़ा गया चिह्नित करें",
    "notifications.markAllRead": "सभी पढ़े गए चिह्नित करें",
    "notifications.clearAll": "सभी साफ़ करें",
    
    // Help Center
    "help.title": "सहायता और समर्थन",
    "help.subtitle": "हम आपकी कैसे मदद कर सकते हैं?",
    "help.faq": "अक्सर पूछे जाने वाले प्रश्न",
    "help.contact": "सहायता से संपर्क करें",
    "help.call": "कॉल",
    "help.email": "ईमेल",
    "help.whatsapp": "WhatsApp",
    "help.sendMessage": "संदेश भेजें",
    "help.yourMessage": "आपका संदेश",
    
    // Toasts
    "toast.signedOut": "साइन आउट हो गया",
    "toast.signedOut.description": "जल्द मिलते हैं!",
    "toast.accountDeleted": "खाता हटा दिया गया",
    "toast.accountDeleted.description": "आपका खाता स्थायी रूप से हटा दिया गया है",
    "toast.deleteFailed": "हटाना विफल",
    "toast.error": "त्रुटि",
    "toast.pushEnabled": "पुश नोटिफिकेशन सक्षम",
    "toast.pushEnabled.description": "आपको इस डिवाइस पर अलर्ट मिलेंगे",
    "toast.pushDisabled": "पुश नोटिफिकेशन अक्षम",
    "toast.permissionDenied": "अनुमति अस्वीकृत",
    "toast.permissionDenied.description": "कृपया अपनी डिवाइस सेटिंग्स में नोटिफिकेशन सक्षम करें",
    "toast.languageChanged": "भाषा बदल दी गई",
    "toast.saved": "सेव हो गया",
    "toast.updated": "अपडेट हो गया",
    "toast.deleted": "हटा दिया गया",
    "toast.copied": "क्लिपबोर्ड पर कॉपी किया गया",
    "toast.uploadSuccess": "अपलोड सफल",
    "toast.uploadFailed": "अपलोड विफल",
    "toast.downloadStarted": "डाउनलोड शुरू हुआ",
    
    // Backup
    "backup.title": "बैकअप और रिस्टोर",
    "backup.subtitle": "अपने डेटा बैकअप प्रबंधित करें",
    "backup.create": "बैकअप बनाएं",
    "backup.restore": "बैकअप रिस्टोर",
    "backup.history": "बैकअप इतिहास",
    "backup.frequency": "बैकअप आवृत्ति",
    "backup.lastBackup": "अंतिम बैकअप",
    "backup.noBackups": "कोई बैकअप नहीं",
    
    // Security
    "security.twoFactor": "दो-कारक प्रमाणीकरण",
    "security.biometric": "बायोमेट्रिक लॉगिन",
    "security.appLock": "ऐप लॉक",
    "security.pinLock": "PIN लॉक",
    "security.setupPin": "PIN सेटअप करें",
    "security.enterPin": "PIN दर्ज करें",
    "security.confirmPin": "PIN पुष्टि करें",
    "security.wrongPin": "गलत PIN",
    "security.pinMismatch": "PIN मेल नहीं खाते",
    "security.pinSet": "PIN सफलतापूर्वक सेट हुआ",
    
    // Inactivity
    "inactivity.title": "निष्क्रियता ट्रिगर",
    "inactivity.subtitle": "आपातकालीन पहुंच सेटअप करें",
    "inactivity.threshold": "निष्क्रियता सीमा",
    "inactivity.days": "दिन",
    "inactivity.message": "कस्टम संदेश",
    "inactivity.enabled": "ट्रिगर सक्षम",
    "inactivity.disabled": "ट्रिगर अक्षम",
    
    // Access Control
    "access.manageAccess": "पहुंच प्रबंधित करें",
    "access.grantAccess": "पहुंच दें",
    "access.revokeAccess": "पहुंच रद्द करें",
    "access.viewOnly": "केवल देखें",
    "access.downloadOnly": "केवल डाउनलोड",
    "access.viewAndDownload": "देखें और डाउनलोड",
    "access.selectNominee": "नामिनी चुनें",
    "access.accessLevel": "पहुंच स्तर",
    "access.noAccess": "पहुंच नहीं दी गई",
  },
  ta: {
    // Common
    "common.welcome": "வரவேற்கிறோம்",
    "common.enabled": "செயல்படுத்தப்பட்டது",
    "common.disabled": "முடக்கப்பட்டது",
    "common.minutes": "நிமிடங்கள்",
    "common.minute": "நிமிடம்",
    "common.save": "சேமிக்கவும்",
    "common.cancel": "ரத்து செய்யவும்",
    "common.delete": "நீக்கவும்",
    "common.edit": "திருத்தவும்",
    "common.add": "சேர்க்கவும்",
    "common.search": "தேடவும்",
    "common.loading": "ஏற்றுகிறது...",
    "common.error": "பிழை",
    "common.success": "வெற்றி",
    "common.confirm": "உறுதிப்படுத்தவும்",
    "common.back": "பின்னால்",
    "common.next": "அடுத்து",
    "common.done": "முடிந்தது",
    "common.close": "மூடவும்",
    "common.yes": "ஆம்",
    "common.no": "இல்லை",
    "common.ok": "சரி",
    "common.documents": "ஆவணங்கள்",
    "common.document": "ஆவணம்",
    "common.noResults": "முடிவுகள் இல்லை",
    "common.tryAgain": "மீண்டும் முயற்சிக்கவும்",
    "common.view": "பார்க்கவும்",
    "common.download": "பதிவிறக்கம்",
    "common.upload": "பதிவேற்றம்",
    "common.create": "உருவாக்கவும்",
    "common.update": "புதுப்பிக்கவும்",
    "common.remove": "நீக்கவும்",
    
    // Navigation
    "nav.home": "முகப்பு",
    "nav.vault": "வால்ட்",
    "nav.settings": "அமைப்புகள்",
    
    // Dashboard
    "dashboard.welcome": "வரவேற்கிறோம்,",
    "dashboard.securityScore": "பாதுகாப்பு மதிப்பெண்",
    "dashboard.docs": "ஆவணங்கள்",
    "dashboard.nominees": "நியமனதாரர்கள்",
    "dashboard.capsules": "காப்சூல்கள்",
    "dashboard.trigger": "தூண்டுதல்",
    "dashboard.quickActions": "விரைவு செயல்கள்",
    "dashboard.noQuickActions": "விரைவு செயல்கள் இயக்கப்படவில்லை",
    "dashboard.triggerEnabled": "தூண்டுதல் செயல்படுத்தப்பட்டது",
    "dashboard.triggerDisabled": "தூண்டுதல் முடக்கப்பட்டது",
    
    // Vault
    "vault.title": "எனது வால்ட்",
    "vault.documents": "ஆவணங்கள்",
    "vault.searchPlaceholder": "ஆவணங்கள், வகைகளைத் தேடுங்கள்...",
    "vault.resultsFound": "{count} முடிவுகள் கண்டறியப்பட்டன",
    "vault.noResults": "முடிவுகள் இல்லை",
    "vault.noResultsDesc": "உங்கள் தேடலை சரிசெய்யவும் அல்லது எல்லா வகைகளையும் பாருங்கள்",
    "vault.clearSearch": "தேடலை அழிக்கவும்",
    "vault.addCategory": "வகை சேர்க்கவும்",
    "vault.categoryName": "வகை பெயர்",
    "vault.categoryNamePlaceholder": "வகை பெயரை உள்ளிடவும்",
    "vault.createCategory": "வகை உருவாக்கவும்",
    "vault.deleteCategory": "வகை நீக்கவும்",
    "vault.deleteCategoryConfirm": "இந்த வகையை நீக்க விரும்புகிறீர்களா?",
    "vault.categoryCreated": "வகை உருவாக்கப்பட்டது!",
    "vault.categoryDeleted": "வகை நீக்கப்பட்டது",
    "vault.cannotDelete": "நீக்க முடியாது",
    "vault.defaultCategoryError": "இயல்புநிலை வகைகளை நீக்க முடியாது",
    "vault.noDocuments": "ஆவணங்கள் இல்லை",
    "vault.uploadFirst": "உங்கள் முதல் ஆவணத்தை பதிவேற்றவும்",
    "vault.manageAccess": "அணுகலை நிர்வகிக்கவும்",
    "vault.whoHasAccess": "யாருக்கு அணுகல் உள்ளது",
    "vault.matches": "பொருத்தங்கள்",
    "vault.match": "பொருத்தம்",
    
    // Documents
    "document.upload": "ஆவணம் பதிவேற்றம்",
    "document.view": "ஆவணம் பார்க்கவும்",
    "document.download": "பதிவிறக்கம்",
    "document.delete": "ஆவணம் நீக்கவும்",
    "document.deleteConfirm": "இந்த ஆவணத்தை நீக்க விரும்புகிறீர்களா?",
    "document.uploaded": "ஆவணம் பதிவேற்றப்பட்டது",
    "document.deleted": "ஆவணம் நீக்கப்பட்டது",
    "document.lock": "ஆவணம் பூட்டவும்",
    "document.unlock": "ஆவணம் திறக்கவும்",
    "document.password": "கடவுச்சொல்",
    "document.confirmPassword": "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    "document.fromDevice": "சாதனத்திலிருந்து",
    "document.fromGoogleDrive": "Google Drive இலிருந்து",
    "document.scanDocument": "ஆவணம் ஸ்கேன்",
    "document.maxSize": "அதிகபட்ச கோப்பு அளவு: 20MB",
    
    // Nominees
    "nominee.title": "நியமனதாரர்கள்",
    "nominee.subtitle": "உங்கள் நம்பகமான தொடர்புகளை நிர்வகிக்கவும்",
    "nominee.add": "நியமனதாரர் சேர்க்கவும்",
    "nominee.edit": "நியமனதாரர் திருத்தவும்",
    "nominee.delete": "நியமனதாரர் நீக்கவும்",
    "nominee.deleteConfirm": "இந்த நியமனதாரரை நீக்க விரும்புகிறீர்களா?",
    "nominee.fullName": "முழு பெயர்",
    "nominee.email": "மின்னஞ்சல்",
    "nominee.phone": "தொலைபேசி",
    "nominee.relation": "உறவு",
    "nominee.pending": "நிலுவையில்",
    "nominee.verified": "சரிபார்க்கப்பட்டது",
    "nominee.sendVerification": "சரிபார்ப்பு அனுப்பவும்",
    "nominee.resendVerification": "சரிபார்ப்பு மீண்டும் அனுப்பவும்",
    "nominee.noNominees": "நியமனதாரர்கள் சேர்க்கப்படவில்லை",
    "nominee.addFirst": "அணுகலைப் பகிர உங்கள் முதல் நியமனதாரரைச் சேர்க்கவும்",
    
    // Time Capsule
    "timeCapsule.title": "டைம் காப்சூல்",
    "timeCapsule.subtitle": "எதிர்காலத்திற்கான செய்திகளை திட்டமிடுங்கள்",
    "timeCapsule.create": "டைம் காப்சூல் உருவாக்கவும்",
    "timeCapsule.edit": "டைம் காப்சூல் திருத்தவும்",
    "timeCapsule.delete": "டைம் காப்சூல் நீக்கவும்",
    "timeCapsule.deleteConfirm": "இந்த டைம் காப்சூலை நீக்க விரும்புகிறீர்களா?",
    "timeCapsule.messageTitle": "தலைப்பு",
    "timeCapsule.message": "செய்தி",
    "timeCapsule.recipientEmail": "பெறுநர் மின்னஞ்சல்",
    "timeCapsule.releaseDate": "வெளியீட்டு தேதி",
    "timeCapsule.attachment": "இணைப்பு",
    "timeCapsule.addAttachment": "இணைப்பு சேர்க்கவும்",
    "timeCapsule.scheduled": "திட்டமிடப்பட்டது",
    "timeCapsule.released": "வெளியிடப்பட்டது",
    "timeCapsule.noCapsules": "டைம் காப்சூல்கள் இல்லை",
    "timeCapsule.createFirst": "உங்கள் முதல் டைம் காப்சூலை உருவாக்குங்கள்",
    
    // Profile
    "profile.title": "சுயவிவரம்",
    "profile.subtitle": "உங்கள் சுயவிவரத்தை நிர்வகிக்கவும்",
    "profile.edit": "சுயவிவரம் திருத்தவும்",
    "profile.fullName": "முழு பெயர்",
    "profile.email": "மின்னஞ்சல்",
    "profile.phone": "தொலைபேசி",
    "profile.dateOfBirth": "பிறந்த தேதி",
    "profile.changePhoto": "புகைப்படம் மாற்றவும்",
    "profile.updated": "சுயவிவரம் புதுப்பிக்கப்பட்டது",
    
    // Settings page
    "settings.title": "அமைப்புகள்",
    "settings.subtitle": "உங்கள் விருப்பங்களை நிர்வகிக்கவும்",
    "settings.changePassword": "கடவுச்சொல்லை மாற்று",
    "settings.changePassword.subtitle": "உங்கள் கடவுச்சொல்லை புதுப்பிக்கவும்",
    "settings.emailPreferences": "மின்னஞ்சல் விருப்பங்கள்",
    "settings.emailPreferences.subtitle": "மின்னஞ்சல் அமைப்புகளை நிர்வகிக்கவும்",
    "settings.twoFactorAuth": "இரு-காரணி அங்கீகாரம்",
    "settings.twoFactorAuth.subtitle": "கூடுதல் பாதுகாப்பு",
    "settings.twoFactorAuth.enabled": "செயல்படுத்தப்பட்டது",
    "settings.appLock": "ஆப் லாக்",
    "settings.appLock.subtitle": "PIN அல்லது பயோமெட்ரிக்",
    "settings.appLock.active": "செயலில்",
    "settings.activeSessions": "செயலில் உள்ள அமர்வுகள்",
    "settings.activeSessions.subtitle": "உள்நுழைந்த சாதனங்களை நிர்வகிக்கவும்",
    "settings.pushNotifications": "புஷ் அறிவிப்புகள்",
    "settings.pushNotifications.subtitle": "மொபைல் எச்சரிக்கைகளைப் பெறுங்கள்",
    "settings.pushNotifications.mobileOnly": "மொபைல் ஆப்பில் மட்டுமே கிடைக்கும்",
    "settings.autoLockTimeout": "ஆட்டோ லாக் நேரம்",
    "settings.backupRestore": "காப்புப்பிரதி & மீட்டமை",
    "settings.backupRestore.subtitle": "உங்கள் வால்ட்டை ஏற்றுமதி அல்லது மீட்டமைக்கவும்",
    "settings.helpSupport": "உதவி & ஆதரவு",
    "settings.helpSupport.subtitle": "FAQகள், வழிகாட்டிகள் & தொடர்பு",
    "settings.language": "மொழி",
    "settings.language.subtitle": "ஆப் மொழியை மாற்றவும்",
    "settings.signOut": "வெளியேறு",
    "settings.deleteAccount": "கணக்கை நீக்கு",
    "settings.deleteAccount.title": "கணக்கை நீக்கு",
    "settings.deleteAccount.description": "உங்கள் கணக்கை நீக்க விரும்புகிறீர்களா?",
    "settings.deleteAccount.confirm": "கணக்கை நீக்கு",
    "settings.deleting": "நீக்கப்படுகிறது...",
    "settings.appVersion": "ஆப் பதிப்பு 2.0.0",
    
    // Language page
    "language.title": "மொழி",
    "language.subtitle": "உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்",
    "language.current": "தற்போதைய",
    
    // Auth
    "auth.signIn": "உள்நுழைய",
    "auth.signUp": "பதிவு செய்ய",
    "auth.signOut": "வெளியேறு",
    "auth.email": "மின்னஞ்சல்",
    "auth.password": "கடவுச்சொல்",
    "auth.confirmPassword": "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    "auth.forgotPassword": "கடவுச்சொல் மறந்துவிட்டதா?",
    "auth.resetPassword": "கடவுச்சொல் மீட்டமைக்கவும்",
    "auth.newPassword": "புதிய கடவுச்சொல்",
    "auth.currentPassword": "தற்போதைய கடவுச்சொல்",
    "auth.createAccount": "கணக்கு உருவாக்கவும்",
    "auth.alreadyHaveAccount": "ஏற்கனவே கணக்கு உள்ளதா?",
    "auth.dontHaveAccount": "கணக்கு இல்லையா?",
    "auth.signInWithGoogle": "Google மூலம் உள்நுழையவும்",
    "auth.signUpWithGoogle": "Google மூலம் பதிவு செய்யவும்",
    "auth.orContinueWith": "அல்லது தொடரவும்",
    "auth.enterOtp": "OTP உள்ளிடவும்",
    "auth.otpSent": "OTP உங்கள் மின்னஞ்சலுக்கு அனுப்பப்பட்டது",
    "auth.verify": "சரிபார்க்கவும்",
    "auth.resendOtp": "OTP மீண்டும் அனுப்பவும்",
    
    // Notifications
    "notifications.title": "அறிவிப்புகள்",
    "notifications.noNotifications": "அறிவிப்புகள் இல்லை",
    "notifications.markAsRead": "படிக்கப்பட்டதாக குறிக்கவும்",
    "notifications.markAllRead": "அனைத்தையும் படிக்கப்பட்டதாக குறிக்கவும்",
    "notifications.clearAll": "அனைத்தையும் அழிக்கவும்",
    
    // Help Center
    "help.title": "உதவி & ஆதரவு",
    "help.subtitle": "நாங்கள் உங்களுக்கு எவ்வாறு உதவ முடியும்?",
    "help.faq": "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    "help.contact": "ஆதரவைத் தொடர்பு கொள்ளவும்",
    "help.call": "அழைப்பு",
    "help.email": "மின்னஞ்சல்",
    "help.whatsapp": "WhatsApp",
    "help.sendMessage": "செய்தி அனுப்பவும்",
    "help.yourMessage": "உங்கள் செய்தி",
    
    // Toasts
    "toast.signedOut": "வெளியேறியது",
    "toast.signedOut.description": "விரைவில் சந்திப்போம்!",
    "toast.accountDeleted": "கணக்கு நீக்கப்பட்டது",
    "toast.accountDeleted.description": "உங்கள் கணக்கு நிரந்தரமாக நீக்கப்பட்டது",
    "toast.deleteFailed": "நீக்குவது தோல்வியடைந்தது",
    "toast.error": "பிழை",
    "toast.pushEnabled": "புஷ் அறிவிப்புகள் செயல்படுத்தப்பட்டன",
    "toast.pushEnabled.description": "இந்த சாதனத்தில் எச்சரிக்கைகளைப் பெறுவீர்கள்",
    "toast.pushDisabled": "புஷ் அறிவிப்புகள் முடக்கப்பட்டன",
    "toast.permissionDenied": "அனுமதி மறுக்கப்பட்டது",
    "toast.permissionDenied.description": "உங்கள் சாதன அமைப்புகளில் அறிவிப்புகளை செயல்படுத்தவும்",
    "toast.languageChanged": "மொழி மாற்றப்பட்டது",
    "toast.saved": "சேமிக்கப்பட்டது",
    "toast.updated": "புதுப்பிக்கப்பட்டது",
    "toast.deleted": "நீக்கப்பட்டது",
    "toast.copied": "கிளிப்போர்டுக்கு நகலெடுக்கப்பட்டது",
    "toast.uploadSuccess": "பதிவேற்றம் வெற்றி",
    "toast.uploadFailed": "பதிவேற்றம் தோல்வி",
    "toast.downloadStarted": "பதிவிறக்கம் தொடங்கியது",
    
    // Backup
    "backup.title": "காப்புப்பிரதி & மீட்டமை",
    "backup.subtitle": "உங்கள் தரவு காப்புப்பிரதிகளை நிர்வகிக்கவும்",
    "backup.create": "காப்புப்பிரதி உருவாக்கவும்",
    "backup.restore": "காப்புப்பிரதி மீட்டமைக்கவும்",
    "backup.history": "காப்புப்பிரதி வரலாறு",
    "backup.frequency": "காப்புப்பிரதி அதிர்வெண்",
    "backup.lastBackup": "கடைசி காப்புப்பிரதி",
    "backup.noBackups": "காப்புப்பிரதிகள் இல்லை",
    
    // Security
    "security.twoFactor": "இரு-காரணி அங்கீகாரம்",
    "security.biometric": "பயோமெட்ரிக் உள்நுழைவு",
    "security.appLock": "ஆப் லாக்",
    "security.pinLock": "PIN லாக்",
    "security.setupPin": "PIN அமைக்கவும்",
    "security.enterPin": "PIN உள்ளிடவும்",
    "security.confirmPin": "PIN உறுதிப்படுத்தவும்",
    "security.wrongPin": "தவறான PIN",
    "security.pinMismatch": "PIN பொருந்தவில்லை",
    "security.pinSet": "PIN வெற்றிகரமாக அமைக்கப்பட்டது",
    
    // Inactivity
    "inactivity.title": "செயலற்ற தூண்டுதல்",
    "inactivity.subtitle": "அவசர அணுகலை அமைக்கவும்",
    "inactivity.threshold": "செயலற்ற வரம்பு",
    "inactivity.days": "நாட்கள்",
    "inactivity.message": "தனிப்பயன் செய்தி",
    "inactivity.enabled": "தூண்டுதல் செயல்படுத்தப்பட்டது",
    "inactivity.disabled": "தூண்டுதல் முடக்கப்பட்டது",
    
    // Access Control
    "access.manageAccess": "அணுகலை நிர்வகிக்கவும்",
    "access.grantAccess": "அணுகல் வழங்கவும்",
    "access.revokeAccess": "அணுகலை நீக்கவும்",
    "access.viewOnly": "பார்ப்பது மட்டும்",
    "access.downloadOnly": "பதிவிறக்கம் மட்டும்",
    "access.viewAndDownload": "பார்ப்பது & பதிவிறக்கம்",
    "access.selectNominee": "நியமனதாரரைத் தேர்ந்தெடுக்கவும்",
    "access.accessLevel": "அணுகல் நிலை",
    "access.noAccess": "அணுகல் வழங்கப்படவில்லை",
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app_language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    // Update document lang attribute for accessibility
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app_language", lang);
  };

  const t = (key: string, replacements?: Record<string, string | number>): string => {
    let text = translations[language][key] || translations.en[key] || key;
    
    // Handle replacements like {count}
    if (replacements) {
      Object.entries(replacements).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    
    return text;
  };

  const currentLanguage = languages.find((l) => l.code === language) || languages[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
